apiVersion: apps/v1
kind: Deployment
metadata:
  name: team2-app
  namespace: team2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team2-app
  template:
    metadata:
      labels:
        app: team2-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: team2-service
  namespace: team2
spec:
  selector:
    app: team2-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
