apiVersion: apps/v1
kind: DeploymentX
metadata:
  name: team1-app
  namespace: team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team1-app
  template:
    metadata:
      labels:
        app: team1-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: team1-service
  namespace: team1
spec:
  selector:
    app: team1-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
